#!/usr/bin/env python3
"""Durable verification carrier for Slice 1 (raw workspace search).

This carrier proves the *behaviour* of the registered ``honcho_search`` tool
callback and of the ``searchWorkspaceMessages`` transport, not just their source
text. It does so hermetically:

  * No real Honcho requests. ``globalThis.fetch`` is mocked in the routing
    harness and an in-memory ``fetchImpl`` is injected in the edge harness.
  * No real credentials / config. Instead of reassigning ``HOME``, the routing
    harness mocks the ``./config.js`` module (via ``bun:test`` ``mock.module``)
    with a fake ``resolveConfig`` *before* dynamically importing ``tools.ts``, so
    the real ``~/.honcho/config.json`` is never read. The edge harness imports
    ``raw-search.ts`` directly, which reads no config at all. All ``HONCHO_*``
    env vars are stripped from the subprocess as belt-and-suspenders.
  * The temporary Bun harness scripts are written to a scratch dir and removed
    afterwards; source mutations are in-memory only.

Two Bun harnesses are generated at run time:

  routing  -- imports extensions/tools.ts, registers the tools with a mock
              ExtensionAPI + spied deps.getHandles, and drives the *registered*
              honcho_search.execute callback through a mocked global fetch.
              This is the RED/GREEN pivot: the original implementation calls
              handles.session.search (no workspace POST), the new one issues a
              single POST /v3/workspaces/{encoded}/search with body
              {query, limit:10} and never touches getHandles/session.search.

  edge     -- imports extensions/raw-search.ts directly and exercises the
              transport edge cases with an injected fetchImpl: 3500ms default
              budget (incl. body read), timeout, cancellation, non-200, invalid
              JSON, non-array, mixed workspace, missing provenance, exact
              dedupe, id/content conflict, unsupported origin, redirect:error,
              field preservation + retrievedAt, and no-fallback for target=user.
              Skipped (not failed) when raw-search.ts is absent so the RED run
              produces a clean behavioural failure rather than an import error.

Exit code is non-zero if any executed harness reports a failing assertion.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOOLS = REPO / "extensions" / "tools.ts"
RAW_SEARCH = REPO / "extensions" / "raw-search.ts"
CONFIG = REPO / "extensions" / "config.ts"

# Fake, non-secret config. Workspace deliberately contains "/" and " " to prove
# the workspace id is percent-encoded into a single path segment.
FAKE_WORKSPACE = "oh/my pi"
ENCODED_WORKSPACE = "oh%2Fmy%20pi"
FAKE_PEER = "user-alex"
FAKE_AI_PEER = "ai-oh-my-pi"
FAKE_API_KEY = "fake-key-DO-NOT-USE-0000"
OFFICIAL_ORIGIN = "https://api.honcho.dev"
EXPECTED_PATH = f"/v3/workspaces/{ENCODED_WORKSPACE}/search"


def _bun() -> str:
    found = shutil.which("bun")
    if not found:
        print("FATAL: bun not found on PATH; cannot run hermetic harness", file=sys.stderr)
        sys.exit(3)
    return found


# Shared guard is installed before importing product modules. Its persistent
# counter is outside product catch blocks, so swallowed exceptions still fail.
GUARD = r''' 
let failures = 0;
let guardCalls = 0;
function violation(reason) {
  failures++;
  console.log("FAIL GLOBAL_GUARD " + reason);
  throw new Error("mock contract violation");
}
function guardFetch(impl, expectedQuery, workspace = "oh/my pi") {
  return async (url, init) => {
    guardCalls++;
    const expected = "https://api.honcho.dev/v3/workspaces/" + encodeURIComponent(workspace) + "/search";
    if (String(url) !== expected) violation("official origin + full encoded search URL");
    if (init?.method !== "POST") violation("method must be POST");
    let body;
    try { body = JSON.parse(init?.body); } catch { violation("body must be JSON"); }
    if (!body || Array.isArray(body) || Object.keys(body).sort().join(",") !== "limit,query"
        || body.query !== expectedQuery || body.limit !== 10) violation("query + limit10 only");
    return impl(url, init);
  };
}
// Any unexpected default fetch is blocked without ever reaching the network.
globalThis.fetch = guardFetch(() => violation("unexpected default fetch"), "q");
'''

ROUTING_HARNESS = r'''
// Auto-generated by verify-raw-search.py. Exercises the registered honcho_search
// callback through a mocked global fetch. No real network, no real config.
import {{ mock }} from "bun:test";

const OFFICIAL_ORIGIN = "{OFFICIAL_ORIGIN}";
const EXPECTED_PATH = "{EXPECTED_PATH}";
const FAKE_API_KEY = "{FAKE_API_KEY}";
const FAKE_PEER = "{FAKE_PEER}";
const FAKE_AI_PEER = "{FAKE_AI_PEER_PLACEHOLDER}";
const FAKE_WORKSPACE = "{FAKE_WORKSPACE}";

// Credential isolation at the module boundary: replace ./config.js with a fake
// resolveConfig BEFORE tools.ts is imported. This means the real
// ~/.honcho/config.json is never read and HOME never has to be reassigned by the
// Python runner. saveConfig/saveRootField/readHonchoConfig are stubbed as inert
// traps so any attempted config write fails independently of product catches.
mock.module("{CONFIG_IMPORT}", () => ({{
  resolveConfig: () => ({{
    apiKey: FAKE_API_KEY,
    url: OFFICIAL_ORIGIN,
    workspace: FAKE_WORKSPACE,
    peerName: FAKE_PEER,
    aiPeer: FAKE_AI_PEER,
  }}),
  saveConfig: () => violation("config saveConfig write"),
  saveRootField: () => violation("config saveRootField write"),
  readHonchoConfig: () => ({{}}),
}}));

const {{ registerTools }} = await import("{TOOLS_IMPORT}");

function ok(name, cond, extra) {{
  if (cond) {{ console.log("PASS " + name); }}
  else {{ failures++; console.log("FAIL " + name + (extra ? " :: " + extra : "")); }}
}}

// --- minimal chainable zod shim (schemas are never parsed by execute) ---
function zodShim() {{
  const chain = new Proxy(function () {{}}, {{
    get: () => (..._a) => chain,
    apply: () => chain,
  }});
  return new Proxy({{}}, {{ get: () => (..._a) => chain }});
}}

// --- register tools against a mock ExtensionAPI ---
const tools = {{}};
const pi = {{ zod: zodShim(), registerTool: (def) => {{ tools[def.name] = def; }} }};

// deps.getHandles must NOT be called by the new honcho_search (it triggers an
// implicit get-or-create workspace + addPeers write). We still spy it so we can
// assert it is untouched, and so the ORIGINAL implementation has something to
// call (its session.search path is what makes RED fail).
let getHandlesCalls = 0;
let sessionSearchCalls = 0;
const fakeHandles = {{
  userPeerId: FAKE_PEER,
  session: {{ id: "sess-x", search: async (..._a) => {{ sessionSearchCalls++; return []; }} }},
  userPeer: {{}},
  aiPeer: {{}},
  honcho: {{}},
  config: {{ observationMode: "unified" }},
}};
const deps = {{ getHandles: async (_ctx) => {{ getHandlesCalls++; return fakeHandles; }} }};

registerTools(pi, deps);

const search = tools["honcho_search"];
ok("honcho_search registered", !!search && typeof search.execute === "function");
if (!search) {{ process.exit(failures ? 1 : 0); }}

// --- mocked global fetch ---
let fetchCalls = [];
let responder = null; // (call) => {{ ok, status, body }}
let expectedQuery;
globalThis.fetch = async (url, init) => guardFetch(async (url, init) => {{
  const call = {{ url: String(url), init }};
  fetchCalls.push(call);
  const r = responder ? responder(call) : {{ ok: true, status: 200, body: "[]" }};
  if (r.throw) throw r.throw;
  return {{
    ok: r.ok !== undefined ? r.ok : (r.status >= 200 && r.status < 300),
    status: r.status ?? 200,
    async text() {{ return r.body ?? ""; }},
  }};
}}, expectedQuery)(url, init);

const ctx = {{ cwd: "/tmp/does-not-matter" }};

async function invoke(query, target, resp) {{
  expectedQuery = query;
  fetchCalls = [];
  getHandlesCalls = 0;
  sessionSearchCalls = 0;
  responder = () => resp;
  const out = await search.execute("id-1", {{ query, target }}, undefined, undefined, ctx);
  let parsed = null;
  try {{ parsed = JSON.parse(out.content[0].text); }} catch {{ /* leave null */ }}
  return {{ out, parsed }};
}}

function msg(over) {{
  return Object.assign({{
    id: "m1", content: "hello", peer_id: FAKE_PEER, session_id: "s1",
    workspace_id: "{FAKE_WORKSPACE}", metadata: {{ k: "v" }}, created_at: "2026-09-16T07:37:52Z",
    token_count: 3,
  }}, over || {{}});
}}

// ============ Case 1: primary workspace routing (RED/GREEN pivot) ============
{{
  const body = JSON.stringify([
    msg({{ id: "m1", content: "codename A", peer_id: FAKE_PEER }}),
    msg({{ id: "m2", content: "codename B", peer_id: "someone-else" }}),
  ]);
  const {{ out, parsed }} = await invoke("current codename?", "all", {{ ok: true, status: 200, body }});

  ok("exactly one fetch call", fetchCalls.length === 1, "got " + fetchCalls.length);
  const call = fetchCalls[0] || {{}};
  const init = call.init || {{}};
  ok("method is POST", init.method === "POST", init.method);
  let u = null; try {{ u = new URL(call.url); }} catch {{}}
  ok("origin is official", !!u && u.origin === OFFICIAL_ORIGIN, u && u.origin);
  ok("workspace id is percent-encoded into one segment", !!u && u.pathname === EXPECTED_PATH, u && u.pathname);
  ok("redirect:error set", init.redirect === "error", String(init.redirect));
  // body: {{query, limit:10}} exactly, no filters, no peerIds
  let reqBody = null; try {{ reqBody = JSON.parse(init.body); }} catch {{}}
  ok("body has query", !!reqBody && reqBody.query === "current codename?");
  ok("body limit === 10", !!reqBody && reqBody.limit === 10, reqBody && String(reqBody.limit));
  ok("body has NO filters key", !!reqBody && !("filters" in reqBody));
  ok("body has NO peerIds key", !!reqBody && !("peerIds" in reqBody));
  ok("body has only query+limit keys", !!reqBody && Object.keys(reqBody).sort().join(",") === "limit,query",
     reqBody && Object.keys(reqBody).join(","));
  const auth = init.headers && (init.headers.Authorization || init.headers.authorization);
  ok("Authorization is Bearer <key>", auth === "Bearer " + FAKE_API_KEY);
  // routing: new impl must NOT use getHandles or session.search
  ok("getHandles NOT called (no implicit write init)", getHandlesCalls === 0, "calls=" + getHandlesCalls);
  ok("session.search NOT called (workspace path, not session)", sessionSearchCalls === 0, "calls=" + sessionSearchCalls);
  // result shape
  ok("status ok", !!parsed && parsed.status === "ok", parsed && parsed.status);
  ok("scope workspace", !!parsed && parsed.scope === "workspace");
  ok("completeness bounded_semantic", !!parsed && parsed.completeness === "bounded_semantic");
  const hasMsgs = !!parsed && Array.isArray(parsed.messages);
  ok("target=all keeps both authors", hasMsgs && parsed.messages.length === 2, hasMsgs && String(parsed.messages.length));
  const m = hasMsgs ? parsed.messages[0] : null;
  ok("preserves id/content/workspace/session/peer/createdAt",
     !!m && m.id === "m1" && m.content === "codename A" && m.workspaceId === "{FAKE_WORKSPACE}"
        && m.sessionId === "s1" && m.peerId === FAKE_PEER && m.createdAt === "2026-09-16T07:37:52Z");
  ok("retrievedAt present and distinct from createdAt",
     !!parsed && typeof parsed.retrievedAt === "string" && parsed.retrievedAt !== m.createdAt);
  ok("not flagged isError on success", out.isError !== true);
}}

// ============ Case 2: empty results, no fallback, still one POST ============
{{
  const {{ out, parsed }} = await invoke("nothing matches", "all", {{ ok: true, status: 200, body: "[]" }});
  ok("empty: one POST", fetchCalls.length === 1, "got " + fetchCalls.length);
  ok("empty: status empty", !!parsed && parsed.status === "empty", parsed && parsed.status);
  ok("empty: not isError", out.isError !== true);
  ok("empty: partial false", !!parsed && parsed.partial === false);
}}

// ============ Case 3: target=user local author filter, no fallback ============
{{
  const body = JSON.stringify([
    msg({{ id: "a", peer_id: FAKE_PEER, content: "mine" }}),
    msg({{ id: "b", peer_id: FAKE_AI_PEER, content: "machine restated old value" }}),
  ]);
  const {{ parsed }} = await invoke("codename?", "user", {{ ok: true, status: 200, body }});
  ok("user filter: one POST (no fallback second query)", fetchCalls.length === 1, "got " + fetchCalls.length);
  ok("user filter: only developer-authored kept", !!parsed && parsed.messages.length === 1 && parsed.messages[0].peerId === FAKE_PEER,
     parsed && JSON.stringify(parsed.messages.map(x => x.peerId)));
}}

// ==== Case 4: target=user with zero developer matches -> empty, no fallback ==
{{
  const body = JSON.stringify([ msg({{ id: "c", peer_id: FAKE_AI_PEER }}) ]);
  const {{ parsed }} = await invoke("codename?", "user", {{ ok: true, status: 200, body }});
  ok("user empty: one POST only (never re-queries as all)", fetchCalls.length === 1, "got " + fetchCalls.length);
  ok("user empty: status empty (no fabricated all fallback)", !!parsed && parsed.status === "empty" && parsed.messages.length === 0);
}}

// ============ Case 5: non-200 -> error, no secret leak ============
{{
  const {{ out, parsed }} = await invoke("boom", "all", {{ ok: false, status: 500, body: '{{"detail":"SECRET-INTERNAL"}}' }});
  ok("http500: status error", !!parsed && parsed.status === "error", parsed && parsed.status);
  ok("http500: isError flagged", out.isError === true);
  const text = out.content[0].text;
  ok("http500: does not leak api key", text.indexOf(FAKE_API_KEY) === -1);
  ok("http500: does not leak response body", text.indexOf("SECRET-INTERNAL") === -1);
}}

// ============ Case 6: no filters ever, across a filtered query too ==========
{{
  await invoke("q", "user", {{ ok: true, status: 200, body: "[]" }});
  const init = (fetchCalls[0] || {{}}).init || {{}};
  let reqBody = null; try {{ reqBody = JSON.parse(init.body); }} catch {{}}
  ok("user path body still has no filters", !!reqBody && !("filters" in reqBody));
}}

console.log("ROUTING_SUMMARY failures=" + failures);
process.exit(failures ? 1 : 0);
'''


EDGE_HARNESS = r'''
// Auto-generated by verify-raw-search.py. Exercises searchWorkspaceMessages
// transport edge cases with an injected fetchImpl. No real network.
const {{
  searchWorkspaceMessages: productSearch,
  DEFAULT_TIMEOUT_MS,
  RAW_SEARCH_LIMIT,
  OFFICIAL_ORIGIN,
}} = await import("{RAW_SEARCH_IMPORT}");
function searchWorkspaceMessages(config, query, options = {{}}) {{
  const impl = options.fetchImpl ?? globalThis.fetch;
  return productSearch(config, query, {{ ...options, fetchImpl: guardFetch(impl, query, config.workspaceId) }});
}}

const WS = "{FAKE_WORKSPACE}";
const PEER = "{FAKE_PEER}";
const CONFIG = {{ apiKey: "{FAKE_API_KEY}", baseUrl: OFFICIAL_ORIGIN, workspaceId: WS }};

function ok(name, cond, extra) {{
  if (cond) console.log("PASS " + name);
  else {{ failures++; console.log("FAIL " + name + (extra ? " :: " + extra : "")); }}
}}

function rec(over) {{
  return Object.assign({{
    id: "m1", content: "hello", peer_id: PEER, session_id: "s1",
    workspace_id: WS, metadata: {{}}, created_at: "2026-09-16T07:37:52Z", token_count: 1,
  }}, over || {{}});
}}
function fetchReturning(arr, capture) {{
  return async (url, init) => {{
    if (capture) capture.push({{ url: String(url), init }});
    return {{ ok: true, status: 200, async text() {{ return JSON.stringify(arr); }} }};
  }};
}}

// ---- constants ----
ok("DEFAULT_TIMEOUT_MS === 3500", DEFAULT_TIMEOUT_MS === 3500, String(DEFAULT_TIMEOUT_MS));
ok("RAW_SEARCH_LIMIT === 10", RAW_SEARCH_LIMIT === 10, String(RAW_SEARCH_LIMIT));

// ---- invalid JSON ----
{{
  const impl = async () => ({{ ok: true, status: 200, async text() {{ return "not json"; }} }});
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("invalid JSON -> error", r.status === "error" && r.isError === true, r.status);
}}

// ---- non-array JSON ----
{{
  const impl = async () => ({{ ok: true, status: 200, async text() {{ return "{{}}"; }} }});
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("non-array -> error", r.status === "error" && r.isError === true, r.status);
}}

// ---- mixed workspace record isolated ----
{{
  const cap = [];
  const impl = fetchReturning([ rec({{ id: "ok1" }}), rec({{ id: "x", workspace_id: "other-ws" }}) ], cap);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("mixed workspace: valid kept", r.messages.length === 1 && r.messages[0].id === "ok1", JSON.stringify(r.messages.map(m=>m.id)));
  ok("mixed workspace: foreign isolated + counted", r.omittedCount === 1, String(r.omittedCount));
  ok("mixed workspace: partial flagged", r.partial === true);
  ok("mixed workspace: single POST", cap.length === 1, String(cap.length));
}}

// ---- missing provenance isolated, never fabricated ----
{{
  const impl = fetchReturning([
    rec({{ id: "good" }}),
    rec({{ id: "nosession", session_id: undefined }}),
    rec({{ id: "nocreated", created_at: undefined }}),
    rec({{ id: "nopeer", peer_id: undefined }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("provenance: only complete record kept", r.messages.length === 1 && r.messages[0].id === "good");
  ok("provenance: 3 isolated", r.omittedCount === 3, String(r.omittedCount));
  ok("provenance: partial flagged", r.partial === true);
  const kept = r.messages[0];
  ok("provenance: no fabricated fields", kept.sessionId === "s1" && kept.createdAt === "2026-09-16T07:37:52Z" && kept.peerId === PEER);
}}

// ---- exact dedupe (same triple + same content collapses) ----
{{
  const impl = fetchReturning([
    rec({{ id: "dup", session_id: "s1", content: "same" }}),
    rec({{ id: "dup", session_id: "s1", content: "same" }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("exact dedupe: collapses to one", r.messages.length === 1, String(r.messages.length));
  ok("exact dedupe: no conflict recorded", r.conflicts.length === 0);
}}

// ---- id/content conflict: keep first, do not overwrite, mark partial ----
{{
  const impl = fetchReturning([
    rec({{ id: "dup", session_id: "s1", content: "first-value" }}),
    rec({{ id: "dup", session_id: "s1", content: "SECOND-DIFFERENT" }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("conflict: keeps first, not overwritten", r.messages.length === 1 && r.messages[0].content === "first-value",
     JSON.stringify(r.messages.map(m=>m.content)));
  ok("conflict: recorded", r.conflicts.length === 1 && r.conflicts[0].id === "dup", JSON.stringify(r.conflicts));
  ok("conflict: partial flagged", r.partial === true);
}}

// ---- unsupported origin: no request issued ----
{{
  const cap = [];
  const impl = fetchReturning([], cap);
  const r = await searchWorkspaceMessages(
    {{ apiKey: "{FAKE_API_KEY}", baseUrl: "https://evil.example.com", workspaceId: WS }},
    "q", {{ fetchImpl: impl }});
  ok("unsupported origin: status unsupported", r.status === "unsupported", r.status);
  ok("unsupported origin: isError", r.isError === true);
  ok("unsupported origin: NO fetch issued", cap.length === 0, String(cap.length));
}}

// ---- local baseUrl also unsupported (only production origin allowed) ----
{{
  const cap = [];
  const impl = fetchReturning([], cap);
  const r = await searchWorkspaceMessages(
    {{ apiKey: "{FAKE_API_KEY}", baseUrl: "http://127.0.0.1:8000", workspaceId: WS }},
    "q", {{ fetchImpl: impl }});
  ok("local origin: unsupported + no request", r.status === "unsupported" && cap.length === 0);
}}

// ---- empty query rejected without request ----
{{
  const cap = [];
  const impl = fetchReturning([], cap);
  const r = await searchWorkspaceMessages(CONFIG, "   ", {{ fetchImpl: impl }});
  ok("empty query: error, no request", r.status === "error" && cap.length === 0, r.status);
}}

// ---- missing credentials rejected without request ----
{{
  const cap = [];
  const impl = fetchReturning([], cap);
  const r = await searchWorkspaceMessages({{ apiKey: "", baseUrl: OFFICIAL_ORIGIN, workspaceId: WS }}, "q", {{ fetchImpl: impl }});
  ok("no apiKey: error, no request", r.status === "error" && cap.length === 0, r.status);
}}

// ---- target=user without userPeerId rejected without request ----
{{
  const cap = [];
  const impl = fetchReturning([], cap);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ target: "user", fetchImpl: impl }});
  ok("target=user without peer id: error, no request", r.status === "error" && cap.length === 0, r.status);
}}

// ---- timeout: whole budget incl. body read ----
{{
  // fetch resolves fast, but reading the body hangs until aborted.
  const impl = async (_url, init) => ({{
    ok: true, status: 200,
    text() {{ return new Promise((_res, rej) => {{
      const sig = init.signal;
      if (sig) sig.addEventListener("abort", () => rej(new DOMException("aborted", "AbortError")), {{ once: true }});
    }}); }},
  }});
  const t0 = performance.now();
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl, timeoutMs: 60 }});
  const dt = performance.now() - t0;
  ok("timeout (body read): status timeout", r.status === "timeout", r.status);
  ok("timeout: isError", r.isError === true);
  ok("timeout: aborted near budget, not hung", dt < 2000, "dt=" + dt.toFixed(0) + "ms");
}}

// ---- timeout: slow fetch itself ----
{{
  const impl = async (_url, init) => {{
    return await new Promise((_res, rej) => {{
      const sig = init.signal;
      if (sig) sig.addEventListener("abort", () => rej(new DOMException("aborted", "AbortError")), {{ once: true }});
    }});
  }};
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl, timeoutMs: 50 }});
  ok("timeout (slow fetch): status timeout", r.status === "timeout", r.status);
}}

// ---- cancellation via external signal, distinct from timeout ----
{{
  const ac = new AbortController();
  const impl = async (_url, init) => {{
    return await new Promise((_res, rej) => {{
      const sig = init.signal;
      if (sig) sig.addEventListener("abort", () => rej(new DOMException("aborted", "AbortError")), {{ once: true }});
    }});
  }};
  const p = searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl, signal: ac.signal, timeoutMs: 5000 }});
  ac.abort();
  const r = await p;
  ok("cancellation: status cancelled (not timeout)", r.status === "cancelled", r.status);
  ok("cancellation: isError", r.isError === true);
}}

// ---- pre-aborted external signal chains to cancellation ----
{{
  const ac = new AbortController();
  ac.abort();
  const cap = [];
  const impl = async (_url, init) => {{
    if (init.signal && init.signal.aborted) throw new DOMException("aborted", "AbortError");
    cap.push(1);
    return {{ ok: true, status: 200, async text() {{ return "[]"; }} }};
  }};
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl, signal: ac.signal }});
  ok("pre-aborted signal: cancelled", r.status === "cancelled", r.status);
}}

// ---- redirect:error option is passed to fetch; body/path contract ----
{{
  const cap = [];
  const impl = fetchReturning([], cap);
  await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("redirect:error passed to fetch", (cap[0].init || {{}}).redirect === "error", String((cap[0].init||{{}}).redirect));
  const b = JSON.parse((cap[0].init||{{}}).body);
  ok("edge: body is exactly query+limit=10", b.query === "q" && b.limit === 10 && Object.keys(b).length === 2, JSON.stringify(b));
  ok("edge: path percent-encoded", new URL(cap[0].url).pathname === "{EXPECTED_PATH}", new URL(cap[0].url).pathname);
}}

// ============================================================================
// RED cases added for the S1 fix pass (independent mock probes). Each fails
// against the pre-fix transport and passes after the fix.
// ============================================================================

// ---- traversal workspace id (.. and .) rejected BEFORE any request ----
// Pre-fix: encodeURIComponent leaves ".." intact and URL resolution collapses
// /v3/workspaces/../search down to /v3/search, silently issuing a request to the
// wrong path. Post-fix: rejected as an invalid id with no fetch.
{{
  for (const badWs of ["..", "."]) {{
    const cap = [];
    const impl = fetchReturning([], cap);
    const r = await searchWorkspaceMessages(
      {{ apiKey: "{FAKE_API_KEY}", baseUrl: OFFICIAL_ORIGIN, workspaceId: badWs }},
      "q", {{ fetchImpl: impl }});
    ok("traversal ws '" + badWs + "': status error", r.status === "error", r.status);
    ok("traversal ws '" + badWs + "': NO fetch issued", cap.length === 0, String(cap.length));
  }}
}}

// ---- dedupe key is collision-free across the (session,id) boundary ----
// Pre-fix: a space-joined "ws sess id" key conflates (session "a b", id "c")
// with (session "a", id "b c"); the second distinct message is wrongly treated
// as a duplicate/conflict of the first. Post-fix: both survive, no conflict.
{{
  const impl = fetchReturning([
    rec({{ session_id: "a b", id: "c", content: "first message" }}),
    rec({{ session_id: "a", id: "b c", content: "second message" }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("dedupe collision: both distinct records kept", r.messages.length === 2,
     JSON.stringify(r.messages.map(m => m.sessionId + "|" + m.id)));
  ok("dedupe collision: no false conflict recorded", r.conflicts.length === 0, JSON.stringify(r.conflicts));
  ok("dedupe collision: not partial", r.partial === false);
}}

// ---- same triple + same content but different PEER -> provenance conflict ----
// Pre-fix: same key + same content collapsed silently, dropping the divergent
// peer with no signal. Post-fix: keep first, record provenance_conflict, partial.
{{
  const impl = fetchReturning([
    rec({{ id: "dup", session_id: "s1", content: "same", peer_id: PEER }}),
    rec({{ id: "dup", session_id: "s1", content: "same", peer_id: "other-peer" }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("peer conflict: keeps first only", r.messages.length === 1 && r.messages[0].peerId === PEER,
     JSON.stringify(r.messages.map(m => m.peerId)));
  ok("peer conflict: recorded as provenance_conflict",
     r.conflicts.length === 1 && r.conflicts[0].reason === "provenance_conflict", JSON.stringify(r.conflicts));
  ok("peer conflict: partial + counted", r.partial === true && r.omittedCount === 1, String(r.omittedCount));
}}

// ---- same triple + same content but different record TIME -> provenance conflict ----
{{
  const impl = fetchReturning([
    rec({{ id: "dup2", session_id: "s1", content: "same", created_at: "2026-01-01T00:00:00Z" }}),
    rec({{ id: "dup2", session_id: "s1", content: "same", created_at: "2026-01-02T00:00:00Z" }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("time conflict: keeps first record time", r.messages.length === 1 && r.messages[0].createdAt === "2026-01-01T00:00:00Z",
     JSON.stringify(r.messages.map(m => m.createdAt)));
  ok("time conflict: recorded as provenance_conflict",
     r.conflicts.length === 1 && r.conflicts[0].reason === "provenance_conflict", JSON.stringify(r.conflicts));
  ok("time conflict: partial flagged", r.partial === true);
}}

// ---- content conflict still classified as content_conflict (regression) ----
{{
  const impl = fetchReturning([
    rec({{ id: "c1", session_id: "s1", content: "A" }}),
    rec({{ id: "c1", session_id: "s1", content: "B" }}),
  ]);
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl }});
  ok("content conflict: reason=content_conflict",
     r.conflicts.length === 1 && r.conflicts[0].reason === "content_conflict", JSON.stringify(r.conflicts));
}}

// ---- strict base allowlist: userinfo / query / hash / rogue path rejected ----
// Pre-fix: only URL.origin was checked, so a base carrying user:pass@, ?query,
// #hash, or an unexpected path shared the official origin and a request was
// still issued. Post-fix: rejected as unsupported with no fetch.
{{
  const rejected = [
    "https://user:pass@api.honcho.dev",
    "https://api.honcho.dev?token=abc",
    "https://api.honcho.dev#frag",
    "https://api.honcho.dev/rogue",
    "https://api.honcho.dev/v3/workspaces",
    "http://api.honcho.dev",
    "https://api.honcho.dev.evil.com",
  ];
  for (const base of rejected) {{
    const cap = [];
    const impl = fetchReturning([], cap);
    const r = await searchWorkspaceMessages(
      {{ apiKey: "{FAKE_API_KEY}", baseUrl: base, workspaceId: WS }}, "q", {{ fetchImpl: impl }});
    ok("base rejected (unsupported, no fetch): " + base,
       r.status === "unsupported" && cap.length === 0, r.status + "/" + cap.length);
  }}
}}

// ---- strict base allowlist: root and /v3 forms remain accepted ----
{{
  const accepted = [
    "https://api.honcho.dev",
    "https://api.honcho.dev/",
    "https://api.honcho.dev/v3",
    "https://api.honcho.dev/v3/",
  ];
  for (const base of accepted) {{
    const cap = [];
    const impl = fetchReturning([ rec({{}}) ], cap);
    const r = await searchWorkspaceMessages(
      {{ apiKey: "{FAKE_API_KEY}", baseUrl: base, workspaceId: WS }}, "q", {{ fetchImpl: impl }});
    ok("base accepted (single POST): " + base, cap.length === 1, base + " -> " + cap.length);
    ok("base accepted resolves to official search path: " + base,
       cap.length === 1 && new URL(cap[0].url).origin === OFFICIAL_ORIGIN
         && new URL(cap[0].url).pathname === "{EXPECTED_PATH}",
       cap.length === 1 ? new URL(cap[0].url).href : "no-call");
  }}
}}


// ---- uncooperative fetch/body cannot hang past the deadline ----
for (const phase of ["fetch", "body"]) {{
  const never = () => new Promise(() => {{}});
  const impl = phase === "fetch" ? never : async () => ({{ ok: true, status: 200, text: never }});
  const start = performance.now();
  const r = await searchWorkspaceMessages(CONFIG, "q", {{ fetchImpl: impl, timeoutMs: 20 }});
  ok("ignores abort: " + phase + " deadline", r.status === "timeout" && r.isError);
  ok("ignores abort: " + phase + " bounded wait", performance.now() - start < 1500);
}}

// Synchronous parse blocks timer callbacks: it cannot be interrupted, but an
// elapsed deadline must be detected before any successful result is returned.
for (const invalid of [false, true]) {{
  const originalParse = JSON.parse;
  const body = invalid ? "bad-json-deadline" : JSON.stringify([rec({{}})]);
  JSON.parse = (text, ...args) => {{
    if (text === body) {{
      const until = performance.now() + 50;
      while (performance.now() < until) {{}}
    }}
    return originalParse(text, ...args);
  }};
  try {{
    const r = await searchWorkspaceMessages(CONFIG, "q", {{ timeoutMs: 15,
      fetchImpl: async () => ({{ ok: true, status: 200, text: async () => body }}) }});
    ok("decode exceeds deadline (invalid=" + invalid + "): timeout never ok", r.status === "timeout" && r.isError);
  }} finally {{ JSON.parse = originalParse; }}
}}

// Time spent constructing the final result is part of the same deadline.
{{
  const originalParse = JSON.parse;
  const body = JSON.stringify([rec({{}})]);
  JSON.parse = (text, ...args) => {{
    const parsed = originalParse(text, ...args);
    if (text === body) Object.defineProperty(parsed[0], "metadata", {{ get() {{
      const until = performance.now() + 50;
      while (performance.now() < until) {{}}
      return {{}};
    }} }});
    return parsed;
  }};
  try {{
    const r = await searchWorkspaceMessages(CONFIG, "q", {{ timeoutMs: 15,
      fetchImpl: async () => ({{ ok: true, status: 200, text: async () => body }}) }});
    ok("processing exceeds deadline: timeout never ok", r.status === "timeout" && r.isError);
  }} finally {{ JSON.parse = originalParse; }}
}}

console.log("EDGE_SUMMARY failures=" + failures);
process.exit(failures ? 1 : 0);
'''


def _render(tpl: str, **kw: str) -> str:
    # Templates use doubled braces for literal JS braces; single-brace {NAME}
    # tokens are our substitutions. str.format handles both.
    return tpl.format(**kw)


def run_harness(name: str, source: str, workdir: Path, bun: str) -> tuple[int, str]:
    path = workdir / f"harness-{name}.ts"
    path.write_text(GUARD + source, encoding="utf-8")
    env = dict(os.environ)
    # Credential isolation is done INSIDE the harness (routing mocks ./config.js
    # before importing tools.ts; edge imports raw-search.ts, which reads no
    # config at all). We therefore do NOT reassign HOME/USERPROFILE — the real
    # ~/.honcho/config.json is never consulted regardless of HOME. We still strip
    # any HONCHO_* env so a stray real value can never influence a harness even
    # if a future code path fell back to process.env.
    for key in [
        "HONCHO_API_KEY",
        "HONCHO_WORKSPACE",
        "HONCHO_PEER_NAME",
        "HONCHO_USERNAME",
        "HONCHO_AI_PEER",
        "HONCHO_URL",
    ]:
        env.pop(key, None)
    proc = subprocess.run(
        [bun, str(path)],
        cwd=str(REPO),
        env=env,
        capture_output=True,
        text=True,
        timeout=120,
    )
    out = (
        f"$ bun harness-{name} (cwd={REPO})\n"
        f"--- stdout ---\n{proc.stdout}\n"
        f"--- stderr ---\n{proc.stderr}\n"
        f"--- exit: {proc.returncode} ---\n"
    )
    return proc.returncode, out


def main() -> int:
    bun = _bun()
    workdir = Path(tempfile.mkdtemp(prefix="raw-search-verify-"))
    overall = 0
    report: list[str] = []
    try:
        # Routing harness always runs (imports only tools.ts).
        routing_src = _render(
            ROUTING_HARNESS,
            TOOLS_IMPORT=str(TOOLS),
            CONFIG_IMPORT=str(CONFIG),
            OFFICIAL_ORIGIN=OFFICIAL_ORIGIN,
            EXPECTED_PATH=EXPECTED_PATH,
            FAKE_API_KEY=FAKE_API_KEY,
            FAKE_PEER=FAKE_PEER,
            FAKE_WORKSPACE=FAKE_WORKSPACE,
            FAKE_AI_PEER_PLACEHOLDER=FAKE_AI_PEER,
        )
        rc, out = run_harness("routing", routing_src, workdir, bun)
        report.append(out)
        overall = overall or rc

        # Edge harness runs only when raw-search.ts exists (skipped cleanly in RED).
        if RAW_SEARCH.exists():
            edge_src = _render(
                EDGE_HARNESS,
                RAW_SEARCH_IMPORT=str(RAW_SEARCH),
                FAKE_API_KEY=FAKE_API_KEY,
                FAKE_PEER=FAKE_PEER,
                FAKE_WORKSPACE=FAKE_WORKSPACE,
                EXPECTED_PATH=EXPECTED_PATH,
            )
            rc, out = run_harness("edge", edge_src, workdir, bun)
            report.append(out)
            overall = overall or rc

            # Real product mutation via Bun onLoad: no shared source rewrite.
            mutation = r'''
import { plugin } from "bun";
await plugin({ name: "delete-mutation", setup(build) {
  build.onLoad({ filter: /raw-search\.ts$/ }, async ({ path }) => {
    const source = await Bun.file(path).text();
    const needle = 'method: "POST"';
    if (source.split(needle).length !== 2) throw new Error("mutation anchor mismatch");
    console.log("MUTATION_APPLIED POST -> DELETE");
    return { contents: source.replace(needle, 'method: "DELETE"'), loader: "ts" };
  });
} });
'''
            # Use the invalid-JSON case where DELETE otherwise still returns the
            # expected product error: only the external guard makes it RED.
            delete_src = edge_src.split("// ---- non-array JSON ----", 1)[0]
            delete_src += '\nconsole.log("DELETE_SUMMARY failures=" + failures);\nprocess.exit(failures ? 1 : 0);\n'
            rc, out = run_harness("delete-mutation", mutation + delete_src, workdir, bun)
            report.append(out)
            red = (rc == 1 and "MUTATION_APPLIED" in out
                   and "FAIL GLOBAL_GUARD method must be POST" in out
                   and "PASS invalid JSON -> error" in out and "DELETE_SUMMARY failures=1" in out)
            report.append(f"DELETE_MUTATION_EXPECTED_RED={'PASS' if red else 'FAIL'} actual_exit={rc}")
            overall = overall or (0 if red else 1)

            # These attempts are caught like product failures; the guard counter
            # must still make the harness RED (including config write attempts).
            probes = r'''
for (const attempt of [
  () => guardFetch(async () => ({}), "q")("https://evil.example/v3/workspaces/oh%2Fmy%20pi/search", { method: "POST", body: '{"query":"q","limit":10}' }),
  () => guardFetch(async () => ({}), "q")("https://api.honcho.dev/v3/workspaces/oh/my%20pi/search", { method: "POST", body: '{"query":"q","limit":10}' }),
  () => guardFetch(async () => ({}), "q")("https://api.honcho.dev/v3/workspaces/oh%2Fmy%20pi/search", { method: "POST", body: '{"query":"q","limit":10,"filters":{}}' }),
  () => configProbe.saveConfig({}),
  () => configProbe.saveRootField("probe", true),
]) { try { await attempt(); } catch {} }
'''
            probe_src = routing_src.replace(
                'console.log("ROUTING_SUMMARY',
                f'const configProbe = await import("{CONFIG}");\n' + probes + '\nconsole.log("ROUTING_SUMMARY',
            )
            rc, out = run_harness("guard-probes", probe_src, workdir, bun)
            report.append(out)
            red = rc != 0 and out.count("FAIL GLOBAL_GUARD") == 5
            report.append(f"GUARD_PROBES_EXPECTED_RED={'PASS' if red else 'FAIL'} actual_exit={rc}")
            overall = overall or (0 if red else 1)
        else:
            report.append(
                "$ edge harness SKIPPED :: extensions/raw-search.ts absent "
                "(expected during RED against original behaviour)\n"
            )
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    print("\n".join(report))
    if overall == 0:
        print("VERIFY-RAW-SEARCH: GREEN (normal assertions passed; negative controls correctly RED)")
    else:
        print("VERIFY-RAW-SEARCH: FAIL (see failing assertions above)")
    return overall


if __name__ == "__main__":
    sys.exit(main())
